2020-04-21 18:08:57,308 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-21 19:19:52,217 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-21 19:28:45,055 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-22 02:35:21,908 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-22 02:39:29,345 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-22 02:42:57,480 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-22 03:12:52,727 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-22 17:00:58,994 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-22 17:37:14,667 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-22 17:38:34,244 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/sanic/app.py", line 1167, in run
    serve(**server_settings)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/sanic/server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/sanic/server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 519, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 436, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 90, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/core/run.py", line 239, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(endpoints.nlu or nlu_model)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 54, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 274, in __init__
    self._load_interpreter()
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 297, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/nlu/model.py", line 328, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/nlu/components.py", line 718, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/nlu/registry.py", line 231, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 859, in load
    index_tag_id_mapping, label_data, meta, data_example, model_dir
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 935, in _load_model
    model.build_for_predict(predict_data_example)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/utils/tensorflow/models.py", line 201, in build_for_predict
    predict_data.as_tf_dataset, self.batch_predict, eager, "prediction"
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/utils/tensorflow/models.py", line 298, in _get_tf_call_model_function
    tf_call_model_function(next(iter(init_dataset)))
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 964, in wrapper
    user_requested=True,
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 565, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/tmpdj3sfkhj.py", line 48, in tf__batch_predict
    ag__.if_stmt(cond_1, if_true_1, if_false_1, get_state_1, set_state_1, (), ("out['i_scores']", 'self.all_labels_embed'))
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/operators/control_flow.py", line 920, in if_stmt
    return _py_if_stmt(cond, body, orelse)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/operators/control_flow.py", line 1029, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/tmpdj3sfkhj.py", line 37, in if_true_1
    ag__.if_stmt(cond, if_true, if_false, get_state, set_state, (), ('self.all_labels_embed',))
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/operators/control_flow.py", line 920, in if_stmt
    return _py_if_stmt(cond, body, orelse)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/operators/control_flow.py", line 1029, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/tmpdj3sfkhj.py", line 31, in if_true
    _, self.all_labels_embed = ag__.converted_call(self._create_all_labels, (), None, fscope)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 567, in converted_call
    result = converted_f(*effective_args)
  File "/tmp/tmpxkm4nw0g.py", line 13, in tf___create_all_labels
    x = ag__.converted_call(self._create_bow, (self.tf_label_data[LABEL_FEATURES], mask_label, self.label_name), None, fscope)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 526, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 326, in convert
    free_nonglobal_var_names)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 252, in _convert_with_cache
    nodes, include_source_map=True)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/compiler.py", line 138, in ast_to_object
    source_map = origin_info.create_source_map(nodes, source, module.__file__)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/origin_info.py", line 112, in create_source_map
    for before, after in ast_util.parallel_walk(nodes, reparsed_nodes):
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/ast_util.py", line 301, in parallel_walk
    for f in n._fields:
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/socketio/client.py", line 25, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2020-04-22 17:46:43,898 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-22 19:07:32,106 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-22 19:07:55,867 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/sanic/app.py", line 1167, in run
    serve(**server_settings)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/sanic/server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/sanic/server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 519, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 436, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 90, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/core/run.py", line 239, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(endpoints.nlu or nlu_model)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 54, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 274, in __init__
    self._load_interpreter()
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 297, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/nlu/model.py", line 328, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/nlu/components.py", line 718, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/nlu/registry.py", line 231, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 859, in load
    index_tag_id_mapping, label_data, meta, data_example, model_dir
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 922, in _load_model
    config=meta,
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/utils/tensorflow/models.py", line 234, in load
    eager=True,  # no need to build tf graph, eager is faster here
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/utils/tensorflow/models.py", line 148, in fit
    self.train_summary_writer,
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/utils/tensorflow/models.py", line 271, in _batch_loop
    call_model_function(batch_in)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/rasa/utils/tensorflow/models.py", line 193, in train_on_batch
    gradients = tape.gradient(total_loss, self.trainable_variables)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py", line 1029, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/imperative_grad.py", line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py", line 141, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py", line 215, in _SumGrad
    return [array_ops.broadcast_to(grad, input_shape), None]
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 811, in broadcast_to
    tld.op_callbacks, input, shape)
  File "/media/ak/storage3/college/qa-system/venv/lib/python3.7/site-packages/socketio/client.py", line 25, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2020-04-22 19:18:15,363 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-22 19:21:10,635 [INFO ]  Starting Rasa server on http://localhost:5005
